version: '3'
services:
  rent_a_car_service:
    env_file: '.env'
    container_name: rent_a_car_service
    build: .
    ports:
      - '3001:3000'
    volumes:
      - ./web_app/:/var/www/
    restart: always
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    env_file: '.env'
    container_name: postgres_db
    image: postgres:14.7
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "${DB_POSTGRES_PORT}:5432"